# Generated by Django 3.0.2 on 2020-01-22 18:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('idChampion', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('image', models.URLField()),
                ('releaseDate', models.DateField(verbose_name='Release date')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('idPosition', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Position')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('idTier', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('winrate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('idChampion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idChampionTier', to='main.Champion')),
                ('idPosition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idPositionTier', to='main.Position')),
                ('idsChampionCounter', models.ManyToManyField(related_name='ChampionCounter', to='main.Champion')),
                ('idsChampionStronger', models.ManyToManyField(related_name='ChampionStronger', to='main.Champion')),
            ],
            options={
                'ordering': ('level',),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('idSkill', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('description', models.CharField(max_length=3000, verbose_name='Description')),
                ('video', models.URLField()),
                ('champion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Champion', verbose_name='Champion')),
            ],
            options={
                'ordering': ('name', 'description'),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('idPlayer', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('urlPerfil', models.URLField()),
                ('ranking', models.CharField(max_length=30, verbose_name='ranking')),
                ('winrate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('idsChampion', models.ManyToManyField(to='main.Champion')),
            ],
            options={
                'ordering': ('name', 'ranking', 'winrate'),
            },
        ),
    ]
