# Generated by Django 3.0.2 on 2020-01-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='winrate',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
