# Generated by Django 3.0.2 on 2020-01-22 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200122_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='winrate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tier',
            name='winrate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
